In [9]:
import numpy as np

## states

In [10]:
state = {
    0 : 'Idli',
    1: 'Vada',
    2: 'Puri'

}
state

{0: 'Idli', 1: 'Vada', 2: 'Puri'}

## transition matrix

In [11]:
A  = np.array([[0.2,0.6,0.2],
               [0.3,0.0,0.7],
               [0.5,0.0,0.5]])
A


array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

## Random walk on the markov chain


In [15]:
def random_walk(n):
    startState= 0
    currState = startState
    print(state[currState],"===>", end= ' ')
    for i in range(n):
        currState = np.random.choice([0,1,2],p=A[currState])
        print(state[currState],'===>', end=' ')
    print("stop")
random_walk(15)

Idli ===> Idli ===> Vada ===> Puri ===> Puri ===> Idli ===> Vada ===> Idli ===> Vada ===> Puri ===> Idli ===> Puri ===> Puri ===> Puri ===> Idli ===> Idli ===> stop


## Approach 1 Monte Carlo for computing stationary distribution

In [18]:
def monte_carlo(steps):
    startState = 0
    currState =  startState
    pi = np.array([0,0,0])
    pi[startState] = 1
    
    for _ in range(steps):
        currState = np.random.choice([0,1,2],p=A[currState])
        pi[currState] += 1
    print("|| = ", pi/steps)

monte_carlo(10**6)

|| =  [0.352339 0.211207 0.436455]


## Approach 2 Repeated Matrix multiplication

In [21]:
def repeated_matrix_multiplication(steps, A):
    A_n  = A
    for _ in range(steps):
        A_n = np.matmul(A_n,A)
    print("A^n = \n", A_n, '\n')
    print("|| = ", A_n[0])

repeated_matrix_multiplication(10**3,A)

A^n = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

|| =  [0.35211268 0.21126761 0.43661972]


## Finding left eigen vectors

In [24]:
import scipy.linalg

def finding_left_eigen_vector(A):
    values, left  =  scipy.linalg.eig(A, right =  False, left = True)
    print("left eigen vectors = \n", left, '\n')
    print('eigen values= \n' , values)
    pi = left[:,0]
    normalized_pi = [(i/np.sum(pi)).real for i in pi]
    print('Normalized pi \n',normalized_pi)
    return normalized_pi
    
pi_normalized = finding_left_eigen_vector(A)

left eigen vectors = 
 [[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]] 

eigen values= 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]
Normalized pi 
 [0.3521126760563379, 0.21126760563380298, 0.43661971830985913]


## P(Vada==>Puri==>Puri==>Idli) =  ?

In [25]:
def findProbability(sequence, A, pi):
    startState  = sequence[0]
    prob  = pi[startState]
    prevState, currState = startState, startState
    for i in range(1, len(sequence)):
        currState = sequence[i]
        prob *= A[prevState][currState]
        prevState =  currState
    return prob

seq = [1,2,2,0]
print(findProbability(seq,A,pi_normalized))

0.03697183098591552
